[package]
org = "ballerinax"
name = "asb"
version = "0.1.4"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Azure","ServiceBus"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-service-bus"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../asb-native/build/libs/asb-native-0.1.4-all.jar"
groupId = "org.ballerinalang"
artifactId = "asb-native"
module = "asb-native" 
version = "0.1.4"
