[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-alpha9"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-alpha8"


